[package]
name = "minimal"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@iki.fi>"]

[dependencies]
wasm-bindgen = "0.2.33"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
